kind: Namespace
apiVersion: v1
metadata:
  name: ${namespace}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-gettingstarted-deployment
  namespace: ${namespace}
spec:
  selector:
    matchLabels:
      app: python-gettingstarted
  replicas: 3
  template:
    metadata:
      labels:
        app: python-gettingstarted
    spec:
      containers:
        - name: python-gettingstarted
          # enter the path to your image, be sure to include the correct region prefix
          image: us-ashburn-1.ocir.io/fahdabidiroottenancy/telesis-repo-uploadtest:${BUILDRUN_HASH}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: python-gettingstarted-service
  namespace: ${namespace}
  annotations: 
    service.beta.kubernetes.io/oci-load-balancer-shape: "10Mbps"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: python-gettingstarted
